version: "2"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "4040:4040"
    volumes:
      - ./docker-nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker-nginx/logs/nginx-error.log:/var/log/nginx/error.log
      - ./docker-nginx/logs/nginx-access.log:/var/log/nginx/access.log
  web:
    image: webapp
    command: npm start
    volumes:
      - ./client:/app
  server:
    image: webapp
    command: npm run inspect
    ports:
      - "8080:8080"
      - "9229:9229"
    volumes:
      - ./server:/app
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ./mysql:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
  phpfpm:
    image: php:fpm
    volumes:
      - ./php:/usr/share/nginx/html
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8183:80"
    environment:
      PMA_HOST: mysql
