version: "2"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker-nginx/default.conf:/etc/nginx/conf.d/default.conf
  web:
    image: webapp
    command: npm start
    volumes:
      - ./client:/app
  server:
    image: webapp
    command: npm start
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
